name: Update npm package mirror

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: mirror

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Commit Setup
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"

      - name: Download
        run: |
          npm pack @vercel/og
          tar -xzf vercel-og-*.tgz --strip-components=1
          rm vercel-og-*.tgz

      - name: Commit
        run: |
          git add .
          git commit -m "chore: update @vercel/og package ($(date -u '+%Y-%m-%d'))"
          git push origin mirror
